# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ director with Sphinx
sphinx:
  configuration: docs/conf.py

formats: all # build docs in all additional formats: htmlzip, pdf, epub

# Python build requirements
python:
  build.tools.python: 3.7 # "version" is deprecated, replaced by build.tools.python
  install:
    - requirements: req-both.txt
